services:
  - type: web
    name: Interview_Model
    env: python
    runtime: python-3.11.9
    buildCommand: |
      pip install -r requirements.txt
      python -m prisma generate

      
    startCommand: python app.py
